main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from .views import PostListView, LikeView, PostUpdateView, search, UserPostListView, PostCommentView

urlpatterns = [
    path('', PostListView.as_view(), name="homepage"),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    path('like/<int:pk>', LikeView, name='post-like'),
    path('delete/<int:pk>', views.post_delete, name='post-delete'),
    path('update/<int:pk>', PostUpdateView.as_view(), name='post-edit'),
    path('search/', views.search, name='search'),
    path('user_posts/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post-comment/', PostCommentView.as_view(), name="com"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_network/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from user.views import VerificationView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('user.urls')),
    path('activate/<uidb64>/<token>',VerificationView.as_view(),name="activate"),
    path('',include('main.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    # path('social-auth/',include('social_django.urls',namespace="social" )),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('signup/', SignupView.as_view(), name="signup"),
    path('success/',SuccessView.as_view(), name="success"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('edit/', EditProfileView.as_view(), name="edit_profile"),
    path('user/<username>', ViewUserView.as_view(), name="view_user"),
    path('friends/', FriendList.as_view(), name="friend_list"),
    path('all-profiles/', UserList.as_view(), name = "all-profiles-view"),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('send-invite/', send_invatation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('my-invites/accept/', accept_invatation, name='accept-invite'),
    path('my-invites/reject/', reject_invatation, name='reject-invite'),
    path('search_users/', SearchUsers.as_view(), name ="search_users")
]

user/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
from django.conf import settings
from autoslug import AutoSlugField


GENDER_CHOICES = [
    ['male', u"Man"],
    ['female', u"Woman"],
]

REL_CHOICES = [
    ['none', u"Undefined"],
    ['single', u"Single"],
    ['in_a_rel', u"In relationships"],
    ['engaged', u"Engaged"],
    ['married', u"Married"],
    ['in_love', u"in love"],
    ['complicated', u"Complicated"],
]

class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))

        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
        
        available = [profile for profile in profiles if profile not in accepted]
        return available


    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles

    def get_friends(self, me):
        qs = Profile.objects.filter(friends__pk=me.pk)
        return qs


class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=u"User")
    avatar = models.FileField(verbose_name=u"Avatar", default='1.jpg')
    bio = models.TextField(max_length=500, blank=True, null=True, verbose_name=u"Bio", default="no bio...")
    city = models.CharField(max_length=30, blank=True, null=True, verbose_name=u"City")
    birth_date = models.DateField(null=True, blank=True, verbose_name=u"Date of birth")
    gender = models.CharField(max_length=10, verbose_name=u"Gender", choices=GENDER_CHOICES, default="male")
    relationship = models.CharField(max_length=20, verbose_name=u"Relationships", choices=REL_CHOICES, default="none")
    slug = AutoSlugField(populate_from='user')
    friends = models.ManyToManyField(User, blank=True, related_name='friends')

    objects = ProfileManager()


    def __str__(self):
        return str(self.user.username)


    def get_absolute_url(self):

        return "/users/{}".format(self.slug)

    

    def get_likes_given_no(self):
        likes = self.likes1.all()
        total_liked = 0
        for item in likes:
            if item.value=='Like':
                total_liked +=1
        return total_liked

    def get_likes_recieved_no(self):
        posts = self.user_set.all()
        total_liked = 0
        for item in posts:
            total_liked += item.likes.all().count()
        return total_liked


STATUS_CHOICES = (
    ('send','send'),
    ('accepted','accepted'),
    ('remove','remove'),
)

class RelationshipManager(models.Manager):
    def invatations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs



class Relationship(models.Model):

    sender = models.ForeignKey(Profile,on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(Profile,on_delete=models.CASCADE, related_name="receiver")
    status = models.CharField(max_length=8,choices=STATUS_CHOICES)

    objects = RelationshipManager()

    def __str__(self):
        return str(self.sender.user)

        


        

user/forms.py
from django.contrib.auth.models import User
from django.forms.widgets import TextInput, RadioSelect
from django.forms import FileInput, Textarea
from django import forms
from .models import Profile


class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField(widget = forms.TextInput(attrs={'class': 'form-control','placeholder':'Имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control','placeholder':'Почта'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder':'Пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder':'Подтвердите пароль'}))

    class Meta:
        model = User
        fields =['username','email','password','password2']

    def clean_username(self):
        if User.objects.filter(username=self.cleaned_data['username']).exists():
            raise forms.ValidationError('Такой пользователь существует')
        return self.cleaned_data['username']

    

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают')
        elif len(cd['password'])<6:
            raise forms.ValidationError('Слишком короткий пароль')
        return cd['password2']


class NumberInput(TextInput):
    input_type = 'date'


GENDER_CHOICES = [
    ['male', u"Man"],
    ['female', u"Woman"],
]


class ProfileForm(forms.ModelForm):

    bio = forms.CharField(widget = forms.Textarea(attrs = {'rows':'3'}))
    birth_date = forms.DateField(widget = NumberInput(attrs={'type': 'date'}))
    gender = forms.ChoiceField(widget = RadioSelect, choices = GENDER_CHOICES)


    class Meta:
        
        model = Profile
        exclude = ['user','friends']

user/views.py
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import TemplateView, UpdateView, ListView
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_text, DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from .utils import token_generator
from .service import send
from .models import Profile, Relationship
from .forms import UserRegistrationForm, ProfileForm
import random



class LoginView(TemplateView):
    template_name = "login.html"

    def dispatch(self, request, *args, **kwargs):
        context = {}
        if request.method == 'POST':
            user_form = UserRegistrationForm(request.POST)
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")
            else:
                context['error'] = "Неправильный логин или пароль"
        return render(request, self.template_name, context)




class SignupView(TemplateView):
    template_name = "signup.html"

    def dispatch(self, request, *args, **kwargs):
        if request.method == 'POST':
            user_form = UserRegistrationForm(request.POST)
            if user_form.is_valid():
            #Create a new user object but avoid saving it yet
                new_user = user_form.save(commit=False)
            # Set the chosen password
                new_user.set_password(user_form.cleaned_data['password'])
            #Save the User object
                new_user.is_active=False
                new_user.save()
                user_new = new_user
                uidb64 = urlsafe_base64_encode(force_bytes(new_user.pk))

                domain = get_current_site(request).domain
                link = reverse('activate',kwargs={'uidb64':uidb64,'token':token_generator.make_token(new_user)})
                activate_url = "http://" + domain+ link

                subject="Регистрация"
                body="Уважаемый " + new_user.username + " Для активации аккаунта перейдите по ссылке\n"+ activate_url
                send(subject,body,new_user.email)
                return redirect("success")
        else:
            user_form = UserRegistrationForm()
        return render(request, self.template_name, {'user_form': user_form})

    

class VerificationView(TemplateView):
    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None and token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('edit_profile')
            return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
        else:
            return HttpResponse('Activation link is invalid!')



class ProfileView(TemplateView):
    template_name = "profile.html"

    def dispatch(self, request, *args, **kwargs):
        if not Profile.objects.filter(user=request.user).exists():
            return redirect(reverse("edit_profile"))
        context = {
            'selected_user': request.user
        }
        return render(request, self.template_name, context)




class EditProfileView(TemplateView):
    template_name = "edit_profile.html"

    def dispatch(self, request, *args, **kwargs):
        form = ProfileForm(instance=self.get_profile(request.user))
        if request.method == 'POST':
            form = ProfileForm(request.POST, request.FILES, instance=self.get_profile(request.user))
            if form.is_valid():
                form.instance.user = request.user
                form.save()
                messages.success(request, u"Profile has been updated!")
                return redirect(reverse("profile"))
        return render(request, self.template_name, {'form': form})

    def get_profile(self, user):
        try:
            return user.profile
        except:
            return None


class ViewUserView(TemplateView):
    template_name = "profile.html"

    def dispatch(self, request, *args, **kwargs):
        username = kwargs['username']
        try:
            user = User.objects.get(username=username)
            return render(request, self.template_name, {'selected_user': user})
        except:
            return redirect("/")


class SuccessView(TemplateView):
    template_name = "success.html"
    

class FriendList(LoginRequiredMixin,ListView):
    model = Profile
    template_name = 'friend_list.html'
    context_object_name = 'friends'

    def get_queryset(self):
        friends = Profile.objects.get_friends(self.request.user)
        return friends

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        

        return context

 
class SearchUsers(LoginRequiredMixin,ListView):
    model = Profile
    template_name = 'users_list.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        qs = Profile.objects.filter(user__username__icontains=query)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        

        return context



@login_required
def invites_received_view(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invatations_received(profile)
    results = list(map(lambda x: x.sender, qs))

    context = {
        'qs': results,
    }

    return render(request, 'my_invites.html', context)

@login_required
def accept_invatation(request):
    if request.method=="POST":
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('all-profiles-view')

@login_required
def reject_invatation(request):
    if request.method=="POST":
        pk = request.POST.get('profile_pk')
        receiver = Profile.objects.get(user=request.user)
        sender = Profile.objects.get(pk=pk)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('all-profiles-view')


class UserList(LoginRequiredMixin,ListView):
    model = Profile
    template_name = 'users_list.html'

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender

        return context

@login_required
def send_invatation(request):
    if request.method=='POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')

        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('all-profiles-view')
    
@login_required
def remove_from_friends(request):
    if request.method=='POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('all-profiles-view')

user/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

user/templates/edit_profile.html
{% extends 'home.html' %}{% load crispy_forms_tags %}
{% load static %}
{% block content %}

    <div class="container content" style="text-align: center;">
        <div style="display: inline-block; width: 850px;">
            <div class = "form-group">
            <h2>Редактировать профиль</h2>
            <form method="post" class="bootstrap-form" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-success" value="Сохранить">
            </form>
        </div>
        </div>
    </div>
{% endblock %}

user/templates/friend_list.html
{% extends "home.html" %} {% load static %}{% block content %}
<div class="container">

      <div style="display:flex;">
        <a href="{% url 'my-invites-view' %}" style="margin-left: 170px;">Invites </a>
        <a href="{% url 'all-profiles-view' %}" style="margin-left: 40px;">All friends</a>
      </div>
      {% if friends %}
      <div class="card card-signin my-5">
        <div class="card-body" style="width: 500px;">

          {% for user_p in friends %}
          <div class="left_rigth" style="display: flex; justify-content:baseline;border: 1px solid lightskyblue;padding: 5px 5px;">
            <div class = "left" style="position:relative;">
              <a href="{{ user_p.get_absolute_url }}"><img src="{{ user_p.avatar.url }}" class="rounded mr-2" width="40" height="40"/></a>
              <a class="text-dark" style = "margin-left: 10px;" href="{% url 'view_user' user_p %}"><b>{{ user_p }}</b></a>
            </div>
            <div class="right" style="position:absolute;right:30px;">
              <form action="{% url 'remove-friend' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="profile_pk" value={{user_p.pk}}>
                <button type="submit" class="btn btn-outline-danger">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-x" viewBox="0 0 16 16">
                    <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                    <path fill-rule="evenodd" d="M12.146 5.146a.5.5 0 0 1 .708 0L14 6.293l1.146-1.147a.5.5 0 0 1 .708.708L14.707 7l1.147 1.146a.5.5 0 0 1-.708.708L14 7.707l-1.146 1.147a.5.5 0 0 1-.708-.708L13.293 7l-1.147-1.146a.5.5 0 0 1 0-.708z"/>
                  </svg> </button>
              </form>
            </div>
        </div><br>
          {% endfor %}
        </div>
      </div>
      {% else %}
      <div style="display:flex;justify-content: center; margin-left: 160px; margin-top: 30px;">
        <p>You have no friends now!</p>
      </div>
      {% endif %}

</div>
{% endblock content %}

user/templates/login.html
{% extends 'base_registration.html' %}

{% block content %}
  <form method="POST" action="{% url 'login' %}">
    {% csrf_token %}

    {% if error %}
      <p class="text-danger">{{ error }}</p>
    {% endif %}
    <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-user ti-user"></i></span>
        <input type="text" name="username" class="form-control"  placeholder="Ваш логин">
      </div>
    </div>
    
    <hr class="hr-xs">

    <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-lock ti-unlock"></i></span>
        <input type="password" name="password" class="form-control" placeholder="Ваш пароль">
      </div>
    </div>

    <button class="btn btn-primary btn-block" type="submit">ВОЙТИ</button>
    <div class="login-footer">
      <h6>или войдите с помощью</h6>
      <ul class="social-icons">
        <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
      </ul>
    </div>
    <div class="login-links">
      <p>Еще нету аккаунта? <a class="txt-brand" href="{% url 'signup' %}"><font color=#29aafe>Регистрируйся</font></a></p>
      <p><a href="#">Забыли пароль?</a></p>
    </div>
  </form>

{% endblock content %}

user/templates/my_invites.html
{% extends "home.html" %} 
{% load static %}
{% block content%}
<div class="container">
  <div style="display:flex;">
    <a href="{% url 'friend_list' %}" style="margin-left: 170px;">My friends </a>
    <a href="{% url 'all-profiles-view' %}" style="margin-left: 40px;">All friends</a>
  </div>
        {% if qs %}
        <div class="card card-signin my-5">
          <div class="card-body" style="width: 500px;">
            {% for user_p in qs %}

            <div class="left_rigth" style="display: flex; justify-content:baseline;border: 1px solid lightskyblue;padding: 5px 5px;">
              <div class = "left" style="position:relative;">
                <a href="{{ user_p.get_absolute_url }}"><img src="{{ user_p.avatar.url }}" class="rounded mr-2" width="40" height="40"/></a>
                <a class="text-dark" style = "margin-left: 10px;" href="{% url 'view_user' user_p %}"><b>{{ user_p }}</b></a>
              </div>
              <div class="right" style="position:absolute;right:30px;">
                <div style="display: flex;justify-content:baseline;">
                  <form action="{% url 'accept-invite' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{user_p.pk}}>
                    <button type="submit" class="btn btn-outline-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check" viewBox="0 0 16 16">
                            <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                        </svg> </button>
                  </form>
              <form action="{% url 'reject-invite' %}" method="POST" style="margin-left: 5px;">
                {% csrf_token %}
                <input type="hidden" name="profile_pk" value={{user_p.pk}}>
                <button type="submit" class="btn btn-outline-dark">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                    </svg> </button>
              </form>
              </div>
              </div>
          </div><br>
         {% endfor %}
          </div>
        </div>
        {% else %}
        <div style="display: flex;justify-content: center;margin-left: 180px;">
        <p style="margin-top: 30px;">You have no invites now!</p>
      </div>
        {% endif %}
</div>
{% endblock content %}

user/templates/profile.html
{% extends 'home.html' %}
{% load static %}
{% block content %}

    <link rel="stylesheet" href="{% static 'css/profile.css' %}">

    {% for message in messages %}
    {% if message.tags == 'success' %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% elif message.tags == 'error' %}
     <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endif %}
    {% endfor %}
    <div class="container">

         <div class="row" id="real-estates-detail">
         <div class="col-lg-4 col-md-4 col-xs-12">
         <div class="panel panel-default">

         <div class="card" style="width: 18rem;">
            <div class="text-center">
                <strong>User</strong>
                <hr>
                     <img src="{{ selected_user.profile.avatar.url }}" class="avatar-img img-thumbnail">
            <div class="card-body">
              <h5 class="card-title">{{ selected_user.username }}</h5>
              <p class="card-text">{{ selected_user.profile.bio|linebreaks }}</p>
              {% if selected_user.id == user.id %}
              <a class="btn btn-primary" href="{% url 'edit_profile' %}">Edit profile</a>
                {% else %}
                <a class="btn btn-primary" href="#">Write</a>
                {% endif %}
            </div>
          </div>
        </div>

         </div>
         </div>

        <div class="card" style="margin-left: 80px; width: 500px;">
        <div class="container">
            <br>
         </div><br>
         <div class="container">
            <div class="row row-cols-2">
                <dd class="col-sm-6 list-group-item list-group-item-primary">Email</dt>
                <dd class="col-sm-6 list-group-item-secondary">{{ selected_user.email }}</dd>

            </div>
            <div class="row row-cols-2">
                <dd class="col-sm-6 list-group-item list-group-item-primary">City</dt>
                <dd class="col-sm-6 list-group-item-secondary">{{ selected_user.profile.city }}</dd>

            </div>
            <div class="row row-cols-2">
                <dd class="col-sm-6 list-group-item list-group-item-primary">Date of birth</dt>
                <dd class="col-sm-6 list-group-item-secondary">{{ selected_user.profile.birth_date|date:"d M Y" }}</dd>
            </div>
            <div class="row row-cols-2">
                <dd class="col-sm-6 list-group-item list-group-item-primary">Gender</dt>
                <dd class="col-sm-6 list-group-item-secondary">{{ selected_user.profile.get_gender_display }}</dd>
            </div>
            <div class="row row-cols-2">
                <dd class="col-sm-6 list-group-item list-group-item-primary">Relationships</dt>
                <dd class="col-sm-6 list-group-item-secondary">{{ selected_user.profile.get_relationship_display }}</dd>

            </div>
            <div class="row row-cols-2">
                <dd class="col-sm-6 list-group-item list-group-item-primary">Friends</dt>
                <dd class="col-sm-6 list-group-item-secondary">{{ selected_user.profile.friends.count }}</dd>
            </div>
        </div><br>
          </div>
            
         </div>
        </div>

        </div>
{% endblock content %}

user/templates/signup.html
{% extends 'base_registration.html' %}
    {% block content %}
        <form method="POST">
          {% csrf_token %}
            {% for field in user_form %}

              <div class="form-group">
              <div class="input-group">
              <span class="input-group-addon">
                {% if field == user_form.username %}
                  <i class="fa fa-user ti-user"></i>
                {% endif %}
                {% if field == user_form.email %}
                  <i class="fa fa-envelope"></i>
                {% endif %}
                {% if field == user_form.password or field == user_form.password2 %}
                  <i class="fa fa-lock ti-unlock"></i>
                {% endif %}
              </span>
                {{ field }}
                {% if field.errors %}
                <p style="text-align: left;color:red;">{{ field.errors.as_text }}</p>
                {% endif %}
                </div>
                </div>
              {% endfor %}
          <button class="btn btn-primary btn-block" type="submit">Регистрация</button>
          <div class="login-links">
            <p class="text-center">Есть аккаунт? <a class="txt-brand" href="{% url 'login' %}"><font color=#29aafe>Войти</font></a></p>
          </div>
        </form>
    {% endblock content %}